[colors.primary]
background = '#122222'
foreground = '#00FF00' 

[colors.cursor]
text = '#122222'
cursor = '#FF00FF'

[colors.selection]
text = '#122222'
background = '#00FF00'

[colors.normal]
black   = '#1d1f21'
red     = '#FF5555'
green   = '#00FF00'
yellow  = '#F1FA8C'
blue    = '#3D91FF'
magenta = '#FF79C6'
cyan    = '#8BE9FD'
white   = '#BFBFBF'

[colors.bright]
black   = '#4D4D4D'
red     = '#FF6E67'
green   = '#50FA7B'
yellow  = '#FFFFA5'
blue    = '#73AFFF'
magenta = '#FF92DF'
cyan    = '#A4FFFF'
white   = '#FFFFFF'

[colors.search]
matches = { foreground = '#122222', background = '#00FF00' }
focused_match = { foreground = '#122222', background = '#FF00FF' }

[colors.hints]
start = { foreground = '#122222', background = '#FFFF66' }
end = { foreground = '#FFFF66', background = '#122222' }
